services:
  db:
    image: postgres
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  backend:
    build:
      context: .
      target: backend
    command: /bin/bash -c "sleep 10; python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: django
    volumes:
      - ./accounts:/app/accounts
      - ./server:/app/server
      - ./storage:/app/storage
      - static_volume:/app/static
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=django_db
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - db

  frontend:
    build:
      context: .
      target: frontend-serve
    container_name: react
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
  nginx:
    build:
      context: .
      target: nginx-point
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

volumes:
  postgres_data:
  static_volume:
